//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 09:16:39 AM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://collinsk.com/employee_details_soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.collinsk.employee_details_soap;
